---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nikjooma/nikjoo_app
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -avz --exclude '.git' --exclude 'node_modules' --exclude '.cpanel.yml' * $DEPLOYPATH
